/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface P2PConfig {
  /** Port to listen on (0 = random) */
  listenPort: number
  /** Bootstrap node multiaddresses (e.g. "/ip4/127.0.0.1/tcp/4001/p2p/12D3KooW...") */
  bootstrapPeers: Array<string>
  /** User's chosen nickname */
  nickname: string
  /** Path to persist the Ed25519 identity keypair */
  identityPath?: string
}
export declare class NexusNode {
  constructor()
  /** Start the P2P node. The callback receives JSON-encoded P2PEvent objects. */
  start(config: P2PConfig, callback: (event: string) => void): Promise<string>
  joinRoom(room: string): Promise<void>
  leaveRoom(room: string): Promise<void>
  sendMessage(room: string, text: string): Promise<void>
  sendDm(peerId: string, text: string): Promise<void>
  setNickname(nickname: string): Promise<void>
  getPeers(): Promise<void>
  indexFolder(folderPath: string): Promise<void>
  getFileIndex(): Promise<void>
  startDownload(contentHash: string, fileName: string, savePath: string): Promise<void>
  pauseDownload(contentHash: string): Promise<void>
  resumeDownload(contentHash: string): Promise<void>
  cancelDownload(contentHash: string): Promise<void>
  getActiveDownloads(): Promise<void>
  addPeer(multiaddr: string): Promise<void>
  stop(): Promise<void>
}
